### ISSUE TITLE
Doesn't work on quarantined subreddits.

### ISSUE THREAD

**Issue by XLR-XR** [Pomax/reddit-image-catch-up#4]
Doesn't work on quarantined subreddits.

```reddit-image-catch-up-master node catch-up.js 
Loading config from /Users/x/Downloads/reddit-image-catch-up-master/package.json
Catching up on smuggies/new
(node:11234) UnhandledPromiseRejectionWarning: Error: Status code 403
    at ClientRequest.<anonymous> (/Users/x/Downloads/reddit-image-catch-up-master/node_modules/rss-parser/lib/parser.js:91:25)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:201:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:452:22)
    at TLSSocket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at TLSSocket.Readable.push (_stream_readable.js:226:10)
(node:11234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11234) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Pomax** [comment]
This is effectively an RSS reader, and I'm not sure there is a way to "securely" get an RSS feed for subreddits like that? I'd imagine reddit won't honour any `https://username:password@reddit.com/r/quarantined/new.rss` because that would probably lead to you storing your credentials in a file that can be found by anyone looking for it =(

I'll add a bit about subreddits that _require_ login not being supported in the README.md and add a nicer console log than "a stack trace" to the script.

**Comment by Pomax** [comment]
I've updated the script so that the output is now:
```
>node catch-up.js -c test.config.json
Loading config from J:\Junctions\Git\projects\reddit-image-catch-up\test.config.json
Catching up on smuggies/new
It looks like "smuggies" is a private subreddit, and so cannot be caught up on via RSS

You're all caught up!
```

**Comment by Pomax** [comment]
with the README updated a tiny bit, so that the very first paragraph now makes it explicit this is an RSS reader, and works for public image subreddits.
